### ISSUE TITLE
Simplify file structure

### ISSUE THREAD

**Issue by joelfischerr** [kellertuer/Kartei#12]
As most of the files are not used very often by the user, I propose to put them into a separate folder like this:

```
├── Kartei
│   ├── kartei.a5printstyle.tex
│   ├── kartei.a5printstylerotation.tex
│   ├── kartei.a6printstyle.tex
│   ├── kartei.a6printstylerotation.tex
│   ├── kartei.a7printstyle.tex
│   ├── kartei.a7printstylerotation.tex
│   ├── kartei.a8printstyle.tex
│   ├── kartei.a8printstylerotation.tex
│   ├── kartei.a9printstyle.tex
│   ├── kartei.a9printstylerotation.tex
│   ├── kartei.cls
│   ├── kartei.pageshipout.tex
│   ├── kartei.print.tex
│   ├── kartei.tableofcontents.tex
│   └── texput.log
├── Readme.md
├── beispiel.pdf
├── beispiel.tex
├── manual.pdf
├── manual.tex
├── manualexample1.pdf
└── manualexample1.tex
```

This is how the files are currently structured in my develop branch (unfortunately with some other things as well, as I am new to git and made a mess).

**Comment by MaxMatti** [comment]
Creating an issue probably won't solve the problem, you should create a pull request:

- fork the repo (using the web-interface)
- clone the repo locally
- checkout the last commit
- make the changes you would like to see
- create a commit, push it to your github repo
- create the pull request (using the web-interface)

If you screwed up you local git repo you can always do a `git reset --hard` or just remove the folder and clone the repo again.

**Comment by joelfischerr** [comment]
I thought that I'd start an issue/discussion before creating the pull request, but in hindsight creating a pull request would have been better.
I'll create a pull request later.

**Comment by MaxMatti** [comment]
Afaik pull requests can be discussed just like issues and most project maintainers prefer that, however I can't speak for @kellertuer.
