### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by k0377** [kellertuer/Kartei#7]
I want to install this "packages" but I dont like to be in the same folder to create my flashcards. I'm using orgmode so this would be a real mess to deal with. How do I install on my pc so I dont need to care about these files anymore? I read something about `texthash` but I'm unsure how to use it.

**Comment by k0377** [comment]
i copied the repo to `/usr/share/texmf-dist/` and run `texhash` but I still get an error about not finding `Kartei.cls`:

```
manu:~/ $ pdflatex beispiel.tex                                                                                              [23:11:17]
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./beispiel.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

! LaTeX Error: File `kartei.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: X
```

**Comment by kellertuer** [comment]
May I ask what orgmode is? Which OS are you running on? Linux? Then your way would be to use the local `~/texmf/tex/latex/local/` directory which would be a local installation, see http://tex.stackexchange.com/questions/1137/where-do-i-place-my-own-sty-or-cls-files-to-make-them-available-to-all-my-te

I hope that helps.

**Comment by k0377** [comment]
> [Org mode](http://orgmode.org) is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system.

You can export your files written in org to a lot of formats: 
* latex beamer, 
* documents, 
* libreoffice, 
* markdown, 
* pdf, 
* html
* ical

But you also can tell org a different documentclass to use. 

Thanks, this solved my issue! I prefer to place the file in `/usr/share/texmf-dist/tex/latex/kartei` so I dont need the texmf folder in my home dir. Works great!

**Comment by kellertuer** [comment]
Sounds nice, maybe i'll take a look at that; and nice, that the problem was solved and the package now works fine :)
